<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var \Perspective\ProductByID\Helper\SpecificProductCategories $helper */
/** @var \Perspective\ProductByID\Helper\SpecificProductCategories $block */
//$helper = $this->helper(\Perspective\ProductByID\Helper\ProductById::class);
//$product = $helper->getProductById();
//$productSku = $helper->getProductBySku();
?>
<?php
$productId = 25; // YOUR PRODUCT ID
$product = $block->getProductById($productId);
 
// for current product
// $product = $block->getCurrentProduct();
 
$categoryIds = $product->getCategoryIds();
 
$categories = $block->getCategoryCollection()
                    ->addAttributeToFilter('entity_id', $categoryIds);
                    
foreach ($categories as $category) {
    echo $category->getName() . '<br>';
}
?>

    



