<?php
/** @var $block Link */

use City\Definition\Block\Link;

?>
<?php
$buttonTitle = __('Location');
$city = $block->showCity();
?>

<div>
    <button title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
            type="submit" id="modal-btn-city123"
            data-mage-init='{"city-definition" : {}}'><span><?= $block->escapeHtmlAttr($buttonTitle)?></span>
    </button>
    <div>
        <span>
            <?= $block->escapeHtmlAttr($city)?>
        </span>
    </div>
</div>

<div id="modal-content-city123">
    <div class="modal-inner-content">
        <form class="form contact" id="city123" method="post"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <div class="field note no-label">
                <?= $block->escapeHtml(__('Your city?')) ?>
            </div>
            <div class="field city required">
                <div class="control">
                    <input name="city" id="city" title=""
                           value="<?= $block->escapeHtmlAttr($city)?>" class="input-text" type="tel"
                           data-validate="{required:true, 'validate-city':true}"/>
                </div>
            </div>
        </form>
    </div>
</div>


