<?php
/** @var $block \Perspective\YourCity\Block\Link */
$citiesList = $block->getCitiesList();
$jsonCitiesList = json_encode($citiesList, JSON_HEX_APOS);
$ulrChangeCity = $block->getAjaxUrlChangeCity();
$ulrCity = $block->getAjaxUrlCity();
?>
<li>
    <a id="your_city_id" class="open-modal_city-btn">
        <?= __('Your City:') . ' ';?>
    </a>
</li>

<span id="wrapper">
    <div class="cover"></div>
    <div class="modal_city">
        <div class="content_city content_body">
            <p>Enter your city</p>
            <form autocomplete="off" action="">
                <div class="autocomplete" style="width:50%;">
                    <input id="your_city_input" class="autocomplete_input_city change_city"
                           type="text" name="yourCity" placeholder="City">
                </div>
            </form>
        </div>
    </div>
</span>



<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        //$.ajax({
        //    type: "POST",
        //    showLoader: true,
        //    url: '<?//= $ulrCity ?>//',
        //    data: {'city_name': ''},
        //    dataType: "json",
        //    success: function (data) {
        //        if (data === " ()") {
        //            document.getElementById('your_city_id').innerText = 'Choose Your City';
        //        } else {
        //            document.getElementById('your_city_id').innerText = "Your City: " + data;
        //        }
        //    }
        //});
        var wrap = $('#wrapper'),
            btn = $('.open-modal_city-btn'),
            modal_city = $('.cover, .modal_city, .content_city');

        btn.on('click', function () {
            modal_city.fadeIn();
        });

        $('.modal_city').click(function () {
            wrap.on('click', function (event) {
                var select = $('.content_city');
                if ($(event.target).closest(select).length)
                    return;
                modal_city.fadeOut();
                wrap.unbind('click');
            });
        });




        function autocomplete(inp, arr) {
            var currentFocus;
            inp.addEventListener("input", function (e) {
                var a, b, i, val = this.value;
                closeAllLists();
                if (!val) {
                    return false;
                }
                currentFocus = -1;
                a = document.createElement("DIV");
                a.setAttribute("id", this.id + "autocomplete-list");
                a.setAttribute("class", "autocomplete-items");
                this.parentNode.appendChild(a);
                for (i = 0; i < arr.length; i++) {
                    if (arr[i][1]) {
                        if (arr[i][1].substr(0, val.length).toUpperCase() === val.toUpperCase()) {
                            b = document.createElement("DIV");
                            b.innerHTML = "<strong>" + arr[i][1].substr(0, val.length) + "</strong>";
                            b.innerHTML += arr[i][1].substr(val.length);
                            b.innerHTML += "<input type='hidden' data-name='"
                                + arr[i][1] + "' value='" + arr[i][0] + "'>";
                            a.appendChild(b);
                        }
                    }
                }
                a.addEventListener("click", function (e) {
                    inp.value = e.target.getElementsByTagName("input")[0].getAttribute('data-name');
                    inp.name = e.target.getElementsByTagName("input")[0].value;
                    closeAllLists();
                    $.ajax({
                        type: "POST",
                        showLoader: true,
                        url: '<?= $ulrChangeCity ?>',
                        data: {'city_id': inp.name, 'city_name': inp.value},
                        dataType: "json",
                        cache: false,
                        async: false,
                        success: function () {
                            document.getElementById('your_city_id').value = inp.value;

                            document.getElementById('your_city_id').innerText = "Your City: " + inp.value;
                        }
                    });
                });
            });
            inp.addEventListener("keydown", function (e) {
                var x = document.getElementById(this.id + "autocomplete-list");
                if (x) x = x.getElementsByTagName("div");
                if (e.keyCode === 40) {
                    currentFocus++;
                    addActive(x);
                } else if (e.keyCode === 38) { //up
                    currentFocus--;
                    addActive(x);
                } else if (e.keyCode === 13) {
                    e.preventDefault();
                    if (currentFocus > -1) {
                        if (x) x[currentFocus].click();
                    }
                }
            });

            function addActive(x) {
                if (!x) return false;
                removeActive(x);
                if (currentFocus >= x.length) currentFocus = 0;
                if (currentFocus < 0) currentFocus = (x.length - 1);
                x[currentFocus].classList.add("autocomplete-active");
            }

            function removeActive(x) {
                for (var i = 0; i < x.length; i++) {
                    x[i].classList.remove("autocomplete-active");
                }
            }

            function closeAllLists(elmnt) {
                var x = document.getElementsByClassName("autocomplete-items");
                for (var i = 0; i < x.length; i++) {
                    if (elmnt !== x[i] && elmnt !== inp) {
                        x[i].parentNode.removeChild(x[i]);
                    }
                }
            }

            document.addEventListener("click", function (e) {
                closeAllLists(e.target);
            });
        }

        var countriesObj = JSON.parse('<?= $jsonCitiesList; ?>');
        var countries = Object.entries(countriesObj);
        autocomplete(document.getElementById("your_city_input"), countries);
    });

</script>

