<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\CatalogWidget\Block\Product\ProductsList;
use Magento\Framework\App\Action\Action;

/** @var ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
$type = 'widget-product-grid';
$mode = 'grid';
$image = 'new_products_content_widget_grid';

$items = $block->getProductCollection()->getItems();

$showWishlist = true;
$showCompare = true;
$showCart = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$description = false;
?>


<style type="text/css">
    .slick-track {
        min-height: 450px;
        padding: 30px;
        margin-left: 30px;
        margin-right: auto;
    }
</style>


<div class="product data items"
     data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 1, "disabled": [3], "disabledState": "disabled"}}'>
    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-1"><?= $block->escapeHtml(__($block->getTitle())) ?></a>
    </div>
    <div id="tab-1" class="item content" data-role="content">





        <div class="block widget block-products-list <?= /* @noEscape */
        $mode ?>">



            <?php if ($block->getTitle()): ?>
                <div class="block-title">
                    <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
                </div>
            <?php endif ?>
            <div class="block-content">
                <?= /* @noEscape */
                '<!-- ' . $image . '-->' ?>
                <div class="products-<?= /* @noEscape */
                $mode ?> <?= /* @noEscape */
                $mode ?>">
                    <ol class="product-items <?= /* @noEscape */
                    $type ?>">


                        <div class="slick-slider">


                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?= /* @noEscape */
                                ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                                <div class="product-item-info">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php if ($templateType): ?>
                                            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>

                                        <?= $block->getProductPriceHtml($_item, $type) ?>

                                        <?= $block->getProductDetailsHtml($_item) ?>

                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-inner">
                                                <div class="product-item-actions">
                                                    <?php if ($showCart): ?>
                                                        <div class="actions-primary">
                                                            <?php if ($_item->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                                <form data-role="tocart-form"
                                                                      data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>"
                                                                      action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                                      method="post">
                                                                    <input type="hidden" name="product"
                                                                           value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                    <input type="hidden" name="<?= /* @noEscape */
                                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                                           value="<?= /* @noEscape */
                                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <button type="submit"
                                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                            class="action tocart primary">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_item->isAvailable()): ?>
                                                                    <div class="stock available">
                                                                        <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                    </div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable">
                                                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                    </div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php if ($showWishlist || $showCompare): ?>
                                                        <div class="actions-secondary" data-role="add-to-links">
                                                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                                <a href="#"
                                                                   data-post='<?= /* @noEscape */
                                                                   $block->getAddToWishlistParams($_item) ?>'
                                                                   class="action towishlist"
                                                                   data-action="add-to-wishlist"
                                                                   title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                                                <a href="#" class="action tocompare"
                                                                   data-post='<?= /* @noEscape */
                                                                   $compareHelper->getPostDataParams($_item) ?>'
                                                                   title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </div>
                    </ol>

                </div>
                <?= $block->getPagerHtml() ?>
            </div>
        </div>
        <?php if ($block->getBlockHtml('formkey')): ?>
        <?php endif; ?>
        <?php endif; ?>
    </div>






    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-2"><?= $block->escapeHtml(__($block->getData('title2'))) ?></a>
    </div>
    <div id="tab-2" class="item content" data-role="content">






        <div class="block widget block-products-list <?= /* @noEscape */
        $mode ?>">



            <?php if ($block->getData('title2')): ?>
                <div class="block-title">
                    <strong><?= $block->escapeHtml(__($block->getData('title2'))) ?></strong>
                </div>
            <?php endif ?>
            <div class="block-content">
                <?= /* @noEscape */
                '<!-- ' . $image . '-->' ?>


                <div class="products-<?= /* @noEscape */
                $mode ?> <?= /* @noEscape */
                $mode ?>">
                    <ol class="product-items <?= /* @noEscape */
                    $type ?>">


                        <div class="slick-slider">


                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?= /* @noEscape */
                                ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                                <div class="product-item-info">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php if ($templateType): ?>
                                            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>

                                        <?= $block->getProductPriceHtml($_item, $type) ?>

                                        <?= $block->getProductDetailsHtml($_item) ?>

                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-inner">
                                                <div class="product-item-actions">
                                                    <?php if ($showCart): ?>
                                                        <div class="actions-primary">
                                                            <?php if ($_item->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                                <form data-role="tocart-form"
                                                                      data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>"
                                                                      action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                                      method="post">
                                                                    <input type="hidden" name="product"
                                                                           value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                    <input type="hidden" name="<?= /* @noEscape */
                                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                                           value="<?= /* @noEscape */
                                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <button type="submit"
                                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                            class="action tocart primary">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_item->isAvailable()): ?>
                                                                    <div class="stock available">
                                                                        <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                    </div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable">
                                                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                    </div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php if ($showWishlist || $showCompare): ?>
                                                        <div class="actions-secondary" data-role="add-to-links">
                                                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                                <a href="#"
                                                                   data-post='<?= /* @noEscape */
                                                                   $block->getAddToWishlistParams($_item) ?>'
                                                                   class="action towishlist"
                                                                   data-action="add-to-wishlist"
                                                                   title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                                                <a href="#" class="action tocompare"
                                                                   data-post='<?= /* @noEscape */
                                                                   $compareHelper->getPostDataParams($_item) ?>'
                                                                   title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </div>
                    </ol>

                </div>
                <?= $block->getPagerHtml() ?>
            </div>
        </div>
        <?php if ($block->getBlockHtml('formkey')): ?>
        <?php endif; ?>
    </div>




    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-3"><?= $block->escapeHtml(__($block->getData('title3'))) ?></a>
    </div>
    <div id="tab-3" class="item content" data-role="content">







        <div class="block widget block-products-list <?= /* @noEscape */
        $mode ?>">



            <?php if ($block->getData('title3')): ?>
                <div class="block-title">
                    <strong><?= $block->escapeHtml(__($block->getData('title3'))) ?></strong>
                </div>
            <?php endif ?>
            <div class="block-content">
                <?= /* @noEscape */
                '<!-- ' . $image . '-->' ?>


                <div class="products-<?= /* @noEscape */
                $mode ?>
                <?= /* @noEscape */
                $mode ?>">

                    <ol class="product-items <?= /* @noEscape */
                    $type ?>">


                        <div class="slick-slider">


                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?= /* @noEscape */
                                ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                                <div class="product-item-info">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php if ($templateType): ?>
                                            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>

                                        <?= $block->getProductPriceHtml($_item, $type) ?>

                                        <?= $block->getProductDetailsHtml($_item) ?>

                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-inner">
                                                <div class="product-item-actions">
                                                    <?php if ($showCart): ?>
                                                        <div class="actions-primary">
                                                            <?php if ($_item->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                                <form data-role="tocart-form"
                                                                      data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>"
                                                                      action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                                      method="post">
                                                                    <input type="hidden" name="product"
                                                                           value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                    <input type="hidden" name="<?= /* @noEscape */
                                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                                           value="<?= /* @noEscape */
                                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <button type="submit"
                                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                            class="action tocart primary">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_item->isAvailable()): ?>
                                                                    <div class="stock available">
                                                                        <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                    </div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable">
                                                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                    </div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php if ($showWishlist || $showCompare): ?>
                                                        <div class="actions-secondary" data-role="add-to-links">
                                                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                                <a href="#"
                                                                   data-post='<?= /* @noEscape */
                                                                   $block->getAddToWishlistParams($_item) ?>'
                                                                   class="action towishlist"
                                                                   data-action="add-to-wishlist"
                                                                   title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                                                <a href="#" class="action tocompare"
                                                                   data-post='<?= /* @noEscape */
                                                                   $compareHelper->getPostDataParams($_item) ?>'
                                                                   title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                </a>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </div>
                    </ol>

                </div>
                <?= $block->getPagerHtml() ?>
            </div>
        </div>
        <?php if ($block->getBlockHtml('formkey')): ?>
        <?php endif; ?>
    </div>
</div>


<script type="text/x-magento-init">
    {
        ".block.widget [data-role=tocart-form]": {
            "Magento_Catalog/js/validate-product": {}
        }
    }


</script>


<script type='text/javascript'>
    require(['jquery', 'slick'], function ($) {
        $(".slick-slider").slick({
            dots: false,
            infinite: false,
            slidesToShow: 5,
            slidesToScroll: 1,
            arrows: true,
            centerPadding: '100px',
            responsive: [{
                breakpoint: 1024,
                settings: {
                    slidesToShow: 3,
                    dots: true,
                }
            },
                {
                    breakpoint: 768,
                    settings: {
                        slidesToShow: 2,
                        dots: true,
                        arrows: false,
                    }
                },
                {
                    breakpoint: 480,
                    settings: {
                        slidesToShow: 1,
                        dots: true,
                        arrows: false,
                    }
                },


            ]
        });
    });
</script>




