   <?php
    /** @var \Perspective\ProductCollectionCategoryPrice\Block\Index $block */
   ?>
      <?php $ids = [23]?>
    <?php $categoryProducts = $block->getProductCollectionByCategories($ids); ?>
    <?php if (!is_null($categoryProducts))  ?>
    <p><?php foreach ($categoryProducts as $product) {
          echo 'Name - '.$product->getName() . '<br />'. 'Price - ' . $product->getPrice() . '<br />' . 'Sku - ' . $product->getSku() . '<br />'. '<br />';
           }?></p>
     <h2>Вывод продуктов из категории  Women - Tops - Jackets, где цена меньше 60$ </h2>
    <table border="1px">
        <th>Name</th>
        <th>Sku</th>
        <th>Price</th>
    <?php if (!is_null($categoryProducts))  ?>
    <p><?php foreach ($categoryProducts as $product) {
           if($product->getPrice()<60 && $product->getPrice()>50){
          echo '<tr><td>'.$product->getName() . '</td><td>'. $product->getSku() . '</td><td>'. $product->getPrice() . '</td></tr>';}}?></p>
    </table>


    



