<?php $id = 123; $_productStock = $block->getStockItem($id);?>
<?php //print_r($_productStock->getData()); ?>
<h2><?php echo 'getQty() - '.$_productStock->getQty(); echo '<br />';?>
<h2><?php echo  'getMinQty() - '.$_productStock->getMinQty(); echo '<br />';?>
<h2><?php echo  'getMinSaleQty() - '.$_productStock->getMinSaleQty(); echo '<br />';?>
<h2><?php echo  'getMaxSaleQty() - '.$_productStock->getMaxSaleQty(); echo '<br />';?>
<h2><?php echo  'getIsInStock() - '.$_productStock->getIsInStock(); echo '<br />'; ?>
    



