<?php

/** @var \TestTasks\TaskThree\Block\Index $block */
?>

<?php if ($block->isCurrentProductSimple()) : ?>
    <?php if ($block->getRulePriceEndDate() !== null || $block->getSpecialPriceEndDate() !== null) : ?>
        <h2>
            <div id="getting-started"></div>

            <script type="text/javascript">
                require([
                    'jquery',
                    'countdown'
                ], function(
                    $, countdown
                ) {
                    jQuery("#getting-started")
                        .countdown("<?= $block->getSmallestDate() ?>", function(event) {
                            jQuery(this).text(
                                event.strftime('%D Days %H Hours %M Minutes %S Seconds')
                            );
                        });
                });
            </script>
        </h2>
        <h3> <?= 'Special Price End Date   -   ' . $block->getSpecialPriceEndDate() ?></h3>
    <?php endif ?>



    <?php if (!$block->getRulesNames() == null) : ?>
        <?php foreach ($block->getRulesNames() as $name) : ?>
            <h3> <?= $name['name'] . '  -  ' . $name['date'] ?> </h3>
        <?php endforeach ?>
    <?php endif ?>
<?php endif ?>