<?php

/** @var \WidgetJs\CloseInPrice\Block\Index $block */
?>
<?php if($block->getPriceDifference()):?>
<div class="image-gallery"></div>
<br>
<?= 'Price Difference: $' . $block->getPriceDifference(); ?>
<br>
<?php
$categoryProducts = $block->getProductsByPriceDifference();
foreach ($categoryProducts as $product) : ?>
    <?= $product->getName() . ' - $' . round($product->getPrice()) . '<br />' ?>
<?php endforeach ?>
<br>
<?= 'Category Max Id: ' . $block->getCurrentCategoryId(); ?>
<br>
<?= 'Category Id by Registry: ' . $block->getCurrentCategoryIdRegistry(); ?>
<br>
<?= 'Category Id by LayerResolver: ' . $block->getCurrentCategoryIdResolver(); ?>
<br>

<script>
    require([
        'jquery',
        'mage/gallery/gallery'
    ], function($, gallery) {
        $(function() {
            $('.image-gallery').each(function(index, element) {
                gallery({
                        options: {
                            "nav": "thumbs",
                            "loop": "true",
                            "arrows": "true"
                        },

                        data: [
                            <?= $block->getProductImageUrlArrayStr(); ?>
                        ],

                        fullscreen: {
                            "navdir": "horizontal"
                        },
                        "breakpoints": {
                            "<breakpoint_name>": {
                                "conditions": {
                                    "max-width": "600px"
                                },
                                "options": {}
                            }
                        }
                    },
                    element);
            });
        });
    });
</script>

<?php endif?>