<?php

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <?= $block->getChildHtml('extra.column.header') ?>
                <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order) : ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>"
                        class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */
                        $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra) : ?>
                        <?php $extra->setOrder($_order); ?>
                        <?= $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */
                        $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>"
                        class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                            <span><?= $block->escapeHtml(__('View Order')) ?></span>
                        </a>
                        <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                            <a href="#" data-post='<?= /* @noEscape */
                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                            </a>
                        <?php endif ?>


                        <button  id='<?= $_order->getRealOrderId() ?>' class="modal-btn"
                                data-mage-init='{"order-modal": {"target": "#modal-content"}}'>
                            <span><?php echo __('Cancel') ?></span>
                        </button>


                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>

<div id="modal-content">
<div class="modal-inner-content">
    <form class="form contact" id="contact-form2"
          method="post" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>



        <fieldset class="fieldset">
            <div class="field note no-label">
                <?= $block->escapeHtml(__('Your request will be solved in 48 hours')) ?>
            </div>
            <input type="text" id="id-button" value="123" class="abc"/>

            <div class="field reason required">
                <label class="label"
                       for="name"><span><?= $block->escapeHtml(__('Choose a reason for order cancellation')) ?></span></label>
                <div class="control">
                    <select name="reason" id="reason"
                           title="<?= $block->escapeHtmlAttr(__('Choose a reason for order cancellation')) ?>" value=""
                           class="input-text" data-validate="{required:true}">
                        <option><?= $block->escapeHtml(__('I am Groot.')) ?></option>
                        <option><?= $block->escapeHtml(__('I am Groot.')) ?></option>
                        <option><?= $block->escapeHtml(__('I am Groot.')) ?></option>
                        <option><?= $block->escapeHtml(__('I am Groot.')) ?></option>
                        <option><?= $block->escapeHtml(__('I am Groot.')) ?></option>
                        <option><?= $block->escapeHtml(__('I am Groot.')) ?></option>
                      </select>
                </div>
            </div>
            <div class="field comment">
                <label class="label" for="comment">
                    <span><?= $block->escapeHtml(__('Leave a comment')) ?></span>
                </label>
                <div class="control">
                    <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Leave a comment')) ?>"
                              class="input-text" cols="5" rows="3"></textarea>
                </div>
            </div>
            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>
    </form>
</div>
</div>






