<?php

/** @var \WidgetJs\ExampleOne\Block\Index $block */

?>
<h2>The input text field with the display date picker.</h2>

<input type="text" name="datepicker" id="datepicker" value="" class="datepicker">
<script>
    require(["jquery", "mage/calendar"], function($) {
        $("#datepicker").datepicker({
            showMonthAfterYear: false,
            dateFormat: 'mm/dd/yy',
            changeMonth: true,
            changeYear: true,
            yearRange: '2000:2020',
        })
    });
</script>

<h2>Current Time and Select specific time using DateTime picker widget.</h2>

<input type="text" name="datetimepicker" id="datetimepicker" value="" class="datetimepicker">
<script>
    require([
        'jquery',
        'mage/calendar'
    ], function($) {
        $('#datetimepicker').datetimepicker({
            dateFormat: 'mm/dd/yy',
            timeFormat: 'HH:mm:ss',
            changeMonth: true,
            changeYear: true,
            showsTime: true
        });
    });
</script>

<h2>Clicking it will display a pop-up.</h2>

<button id="modal-btn">Open Modal</button>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Pop-up title',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: 'modal-close',
                    click: function() {
                        this.closeModal();
                    }
                }]
            };

            modal(options, $('#modal-content'));
            $("#modal-btn").on('click', function() {
                $("#modal-content").modal("openModal");
            });
        }
    );
</script>
<div id="modal-content">
    <div class="modal-inner-content">
        <h2>Modal Title</h2>
        <p>Modal content.....!!</p>
    </div>
</div>

<h2>Tab Widget</h2>

<div class="product info detailed">
    <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
        <div class="data item title" data-role="collapsible" id="tab-label-1">
            <a class="data switch" tabindex="-1" data-toggle="trigger" href="#temp-1" id="tab-label-1-title">
                <?php __("Tab 1"); ?> Tab 1
            </a>
        </div>
        <div class="data item content" aria-labelledby="tab-label-1-title" id="temp-1" data-role="content">
            <?php __("Hello Tab 1 Text"); ?> Hello 1 Text
        </div>
        <div class="data item title" data-role="collapsible" id="tab-label-2">
            <a class="data switch" tabindex="-1" data-toggle="trigger" href="#temp-2" id="tab-label-2-title">
                <?php __("Hello Tab 2 Text"); ?> Tab 2
            </a>
        </div>
        <div class="data item content" aria-labelledby="tab-label-2-title" id="temp-2" data-role="content">
            Hello 2 Text
        </div>
    </div>
</div>

<h2>Dropdown1</h2>

<div class="dropdown-wrapper">
    <div class="showDropdown"> Click to open dropdown </div>
    <div id="dropdown" data-role="dropdownDialog">
        Dropdown content goes here.
    </div>
</div>
<script>
    require(['jquery', 'dropdownDialog'],
        function($, dropdownDialog) {
            $('#dropdown').dropdownDialog({
                appendTo: ".dropdown-wrapper",
                triggerTarget: ".showDropdown",
                timeout: 2000,
                closeOnMouseLeave: false,
                closeOnEscape: true,
                triggerClass: "active",
                parentClass: "active",
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function() {
                        $(this).dropdownDialog("close");
                    }
                }]
            });
        }
    );
</script>

<h2>Dropdown2</h2>

<div class="customer-welcome">
    <button
        data-mage-init='{"dropdown":{}}'
        data-toggle="dropdown"
        class="action"
        data-action="customer-menu-toggle">
            <span><?= $block->escapeHtml(__('Dropdown open button')) ?></span>
    </button>
    <ul data-target="dropdown" class="dropdown-options">
        <li>
            <span class="item"><?= $block->escapeHtml(__('Item 1')) ?></span>
        </li>
        <li>
            <span class="item"><a href="#"><?= $block->escapeHtml(__('Item 2 with link')) ?></a></span>
        </li>
        <li>
            <span class="item"><?= $block->escapeHtml(__('Item 3')) ?></span>
        </li>
    </ul>
</div>

<h2>Accordion</h2>

<div data-mage-init="{&quot;accordion&quot;:{&quot;openedState&quot;: &quot;active&quot;, &quot;collapsible&quot;: true, &quot;active&quot;: false, &quot;multipleCollapsible&quot;: &quot;true&quot;}}">

    <div data-role="collapsible">
        <div class="block-title" data-role="trigger"><span>Title 1</span></div>
    </div>
    <div data-role="content">
        Content 1
    </div>


    <div data-role="collapsible">
        <div class="block-title" data-role="trigger"><span>Title 2</span></div>
    </div>
    <div data-role="content">
        Content 2
    </div>

    <div data-role="collapsible">
        <div class="block-title" data-role="trigger"><span>Title 3</span></div>
    </div>
    <div data-role="content">
        Content 3
    </div>

</div>

<script>
    require([
        'jquery',
        'accordion'
    ], function($) {
        $("#element").accordion();
    });
</script>

<h2>Custom Widget</h2>

<div class="atwix-contacts">
    <div class="name">Name: <?php echo $block->getData('fullname'); ?></div>
    <div class="name">Gender: <?php echo $block->getData('gender'); ?></div>
    <div class="phone">Phone: <?php echo $block->getData('phone'); ?></div>
    <div class="email">Email: <?php echo $block->getData('email'); ?></div>
</div>

