<?php
use Dev101\DynamicSC\Block\DynamicSC;
/**
 * @var DynamicSC $block
 */
$isModuleEnabled= $block->isModuleEnabled();
?>
<?php if ($isModuleEnabled): ?>
    <div id="block-dynamic-sc" data-bind="scope:'dynamic-sc'" class="block">
        <!-- ko template: getTemplate() --><!-- /ko -->

        <script type="text/x-magento-init">
    {
        "#block-dynamic-sc": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }

    }
        </script>

    </div>
<?php endif ?>
