<?php 
$id = '1';
$sku = '24-MB01';
$_product = $block->getProductById($id);
$_product = $block->getProductBySku($sku);
echo '<h2>'.'Width - '.$block->getImageOriginalWidth($_product, 'product_small_image') . '<br /></h2>'; 
echo '<h2>'.'Height - '.$block->getImageOriginalHeight($_product, 'product_small_image') . '<br /></h2>';
echo '<h2>'.'Url - '.$block->getProductImageUrl($_product, 'product_small_image') . '<br /></h2>';
    



